[package]
name = "attestation-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for generating and verifying LP-0005 attestation credentials."

[[bin]]
name = "attest"
path = "src/bin/attest.rs"

[dependencies]
attestation-sdk = { path = "../sdk", version = "0.1.0"  }
attestation-core = { path = "../attestation-core", version = "0.1.0", default-features = false, features = ["std"]  }
attestation-verifier-offchain = { path = "../verifier-offchain", version = "0.1.0"  }
risc0-zkvm = { workspace = true, features = ["std", "client"] }
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["std"] }
serde_json = "1"
bincode = { version = "2", features = ["serde"] }
sha2 = { workspace = true, features = ["std"] }
rand = "0.8"
